channels:
- conda-forge
dependencies:
- python=3.12.6
- pip<=24.2
- pip:
  - mlflow==2.16.0
  - cloudpickle==3.0.0
  - numpy==1.26.1
  - psutil==6.0.0
  - scikit-learn==1.3.1
  - scipy==1.14.1
name: mlflow-env
